/// <reference path="globals/core-js/index.d.ts" />
/// <reference path="globals/jest/index.d.ts" />
/// <reference path="globals/react-dom/index.d.ts" />
/// <reference path="globals/react/index.d.ts" />
/// <reference path="globals/reflect-metadata/index.d.ts" />
/// <reference path="globals/systemjs/index.d.ts" />
/// <reference path="modules/lodash/index.d.ts" />
/// <reference path="modules/webpack/index.d.ts" />
/// <reference path="../node_modules/rexjs/dist/index.d.ts"/>